[GitHub Actions] ci: spring.profiles.active 검증 로직 추가

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,7 +1,5 @@
 name: deploy
 
-#TODO: active profile 사전 확인 하는 코드 추가하기!!
-
 on:
   pull_request:
     branches:
@@ -15,7 +13,38 @@ on:
       - temp
 
 jobs:
+  check-profile:
+    runs-on: ubuntu-22.04
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Check spring.profile.active
+        run: |
+          profile=$(grep -E '^\s*active:\s*' src/main/resources/application.yml | awk '{print $2}')
+          echo "Detected profile: $profile"
+          if [ "$profile" != "prod" ]; then
+            echo "wrong_profile=true" >> $GITHUB_ENV
+          fi
+
+      - name: Create a comment on PR if profile.active is wrong
+        if: env.wrong_profile == 'true'
+        uses: peter-evans/create-or-update-comment@v4
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          issue-number: ${{ github.event.pull_request.number }}
+          body: |
+            ❌ **Check 실패: profile.active 설정**
+            `application.yml`의 `spring.profiles.active` 값을 `prod` 으로 변경 해주세요.
+
+      - name: Fail the job if profile is wrong
+        if: env.wrong_profile == 'true'
+        run: |
+          echo "Profile is not prod. Failing the job."
+          exit 1
+
+
   docker-build-push:
+    needs: check-profile
     runs-on: ubuntu-22.04
     steps:
       - uses: actions/checkout@v4
